version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app_network
    environment:
      - MONGODB_URI=mongodb+srv://inf2003-mongodev:toor@inf2003-part2.i7agx.mongodb.net/?retryWrites=true&w=majority

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
